<a href="https://colab.research.google.com/github/optimus1029384756/machine_learning/blob/main/data_preprocessing_tools_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [10]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
#파이썬 슬라이싱에서 [start:end]로 사용되면 start부터 end 전까지 쓰인다.
y = dataset.iloc[:, -1].values

In [11]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [12]:
m_s=0
for i in x:
  print(i)
  for j in i:
    print(type(j),end="")
  print('')
print(m_s)
print(y)

['France' 44.0 72000.0]
<class 'str'><class 'float'><class 'float'>
['Spain' 27.0 48000.0]
<class 'str'><class 'float'><class 'float'>
['Germany' 30.0 54000.0]
<class 'str'><class 'float'><class 'float'>
['Spain' 38.0 61000.0]
<class 'str'><class 'float'><class 'float'>
['Germany' 40.0 nan]
<class 'str'><class 'float'><class 'float'>
['France' 35.0 58000.0]
<class 'str'><class 'float'><class 'float'>
['Spain' nan 52000.0]
<class 'str'><class 'float'><class 'float'>
['France' 48.0 79000.0]
<class 'str'><class 'float'><class 'float'>
['Germany' 50.0 83000.0]
<class 'str'><class 'float'><class 'float'>
['France' 37.0 67000.0]
<class 'str'><class 'float'><class 'float'>
0
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [14]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [17]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [19]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

## Feature Scaling